"""
failure_catalog.py
==================
Mine story artifacts for recurring failure patterns and update
.copilot/context/failure-catalog.md.

Sources mined (in priority order):
  1. SESSION_STATE.md  →  **Recurring Failures:** field
     (BUILD agents write here during the iteration loop)
  2. US-{id}-VALIDATION.md  →  Plan-Checker History table
     (FAIL rows that story-planner recorded before the plan passed)

The catalog is deduplicated by normalized error text. Duplicate patterns
increment a count so story-planner can weight risk scoring accordingly.

Non-blocking contract: if no patterns are found, exits 0 without touching
the catalog. Designed to be called by close-story after a successful stamp.

Usage:
    uv run ~/.copilot/skills/story-master/scripts/failure_catalog.py \\
        --story-id US-01
    uv run ~/.copilot/skills/story-master/scripts/failure_catalog.py \\
        --story-id US-01 \\
        --stories-dir .copilot/stories \\
        --state-path .copilot/state/SESSION_STATE.md \\
        --catalog-path .copilot/context/failure-catalog.md

Exit codes:
    0 = Success (catalog updated, or no new patterns found)
    1 = Invalid arguments
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

_STORY_ID_RE = re.compile(r"^US-\d+$")

_CATALOG_HEADER = """\
# Failure Catalog

> Auto-generated by `failure_catalog.py`. Do NOT edit manually.
> Updated by `close-story` after each story ships.
> Load in story-planner Phase 0 to inform risk scoring.
"""

_FC_ENTRY_RE = re.compile(
    r"## (FC-\d{3}): (.+?)\n"
    r"- \*\*Count:\*\* (\d+)\n"
    r"- \*\*Last seen:\*\* (.+?)\n"
    r"- \*\*Stories:\*\* (.+?)\n"
    r"- \*\*Source:\*\* (.+?)(?:\n|$)",
)


@dataclass
class FailurePattern:
    fc_id: str
    error_type: str
    count: int
    last_seen: str  # "YYYY-MM-DD (US-NN)"
    stories: list[str] = field(default_factory=list)
    source: str = "SESSION_STATE Recurring Failures / Plan-Checker history"

    @property
    def normalized(self) -> str:
        return re.sub(r"\s+", " ", self.error_type.strip().lower())


def _load_patterns(catalog_path: Path) -> list[FailurePattern]:
    if not catalog_path.exists():
        return []
    content = catalog_path.read_text(encoding="utf-8")
    patterns: list[FailurePattern] = []
    for m in _FC_ENTRY_RE.finditer(content):
        patterns.append(
            FailurePattern(
                fc_id=m.group(1),
                error_type=m.group(2).strip(),
                count=int(m.group(3)),
                last_seen=m.group(4).strip(),
                stories=[s.strip() for s in m.group(5).split(",")],
                source=m.group(6).strip(),
            )
        )
    return patterns


def _next_fc_id(patterns: list[FailurePattern]) -> str:
    if not patterns:
        return "FC-001"
    nums = [int(p.fc_id.split("-")[1]) for p in patterns]
    return f"FC-{max(nums) + 1:03d}"


def _render_catalog(patterns: list[FailurePattern]) -> str:
    lines = [_CATALOG_HEADER]

    lines.append("## Pattern Index\n")
    lines.append("| Pattern ID | Error Type | Count | Last Story | Last Date |")
    lines.append("|---|---|---|---|---|")
    for p in patterns:
        last_story = p.stories[-1] if p.stories else "—"
        last_date = p.last_seen.split(" ")[0]
        lines.append(f"| {p.fc_id} | {p.error_type} | {p.count} | {last_story} | {last_date} |")

    lines.append("\n---\n")

    for p in patterns:
        lines.append(f"## {p.fc_id}: {p.error_type}")
        lines.append(f"- **Count:** {p.count}")
        lines.append(f"- **Last seen:** {p.last_seen}")
        lines.append(f"- **Stories:** {', '.join(p.stories)}")
        lines.append(f"- **Source:** {p.source}")
        lines.append("")

    return "\n".join(lines)


def _extract_recurring_failures(state_path: Path) -> list[str]:
    """Extract bullet items from **Recurring Failures:** in SESSION_STATE.md."""
    if not state_path.exists():
        return []
    content = state_path.read_text(encoding="utf-8")
    m = re.search(
        r"\*\*Recurring Failures:\*\*\s*(.*?)(?=\n\s*-\s*\*\*|\n##|\Z)",
        content,
        re.DOTALL,
    )
    if not m:
        return []
    raw = m.group(1).strip()
    if raw.lower() in ("none", ""):
        return []
    items = [line.lstrip("- ").strip() for line in raw.splitlines() if line.strip() and line.strip().lower() != "none"]
    return [i for i in items if i]


def _extract_plan_checker_failures(validation_path: Path) -> list[str]:
    """Extract FAIL check names from Plan-Checker History table in VALIDATION.md."""
    if not validation_path.exists():
        return []
    content = validation_path.read_text(encoding="utf-8")
    fails: list[str] = []
    for line in content.splitlines():
        if "FAIL" not in line or "|" not in line:
            continue
        parts = [p.strip() for p in line.split("|") if p.strip()]
        if not parts or "---" in parts[0]:
            continue  # skip separator rows
        for part in parts:
            if part.startswith("FAIL:"):
                fails.append(part.removeprefix("FAIL:").strip())
            elif part == "FAIL" and len(parts) > 1:
                # Row-level result column; use first column as the check name
                fails.append(parts[0])
                break
    return fails


def main() -> None:
    parser = argparse.ArgumentParser(description="Update .copilot/context/failure-catalog.md from story artifacts")
    parser.add_argument("--story-id", required=True, help="Story ID, e.g. US-01")
    parser.add_argument(
        "--stories-dir",
        type=Path,
        default=Path(".copilot/stories"),
        help="Directory containing story artifacts (default: .copilot/stories)",
    )
    parser.add_argument(
        "--state-path",
        type=Path,
        default=Path(".copilot/state/SESSION_STATE.md"),
        help="Path to SESSION_STATE.md (default: .copilot/state/SESSION_STATE.md)",
    )
    parser.add_argument(
        "--catalog-path",
        type=Path,
        default=Path(".copilot/context/failure-catalog.md"),
        help="Path to failure catalog (default: .copilot/context/failure-catalog.md)",
    )
    args = parser.parse_args()

    if not _STORY_ID_RE.match(args.story_id):
        print(
            f"[x] Invalid story ID: {args.story_id}. Expected format: US-NN.",
            file=sys.stderr,
        )
        sys.exit(1)

    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    validation_path = args.stories_dir / f"{args.story_id}-VALIDATION.md"

    raw_patterns: list[str] = []
    raw_patterns.extend(_extract_recurring_failures(args.state_path))
    raw_patterns.extend(_extract_plan_checker_failures(validation_path))

    if not raw_patterns:
        print(f"[~] No failure patterns found for {args.story_id}. Catalog unchanged.")
        sys.exit(0)

    # Deduplicate by normalized text while preserving insertion order
    seen: set[str] = set()
    unique: list[str] = []
    for p in raw_patterns:
        key = re.sub(r"\s+", " ", p.strip().lower())
        if key and key not in seen:
            seen.add(key)
            unique.append(p)

    args.catalog_path.parent.mkdir(parents=True, exist_ok=True)
    patterns = _load_patterns(args.catalog_path)

    added = 0
    updated = 0
    for error_type in unique:
        normalized = re.sub(r"\s+", " ", error_type.strip().lower())
        existing = next((p for p in patterns if p.normalized == normalized), None)
        if existing:
            existing.count += 1
            existing.last_seen = f"{today} ({args.story_id})"
            if args.story_id not in existing.stories:
                existing.stories.append(args.story_id)
            updated += 1
        else:
            fc_id = _next_fc_id(patterns)
            patterns.append(
                FailurePattern(
                    fc_id=fc_id,
                    error_type=error_type.strip(),
                    count=1,
                    last_seen=f"{today} ({args.story_id})",
                    stories=[args.story_id],
                )
            )
            added += 1

    args.catalog_path.write_text(_render_catalog(patterns), encoding="utf-8")
    print(f"[+] Failure catalog updated: {added} new pattern(s), {updated} incremented. Path: {args.catalog_path}")


if __name__ == "__main__":
    main()
