"""
generate_review_report.py
=========================
Scaffold a structured Guardian review report from findings.

Usage (agent context):
    from skills.guardian.scripts.generate_review_report import ReviewReport, Finding, Severity
    report = ReviewReport(target="src/auth/service.py")
    report.add(Finding(Severity.CRITICAL, "SQL injection", "auth/service.py", 42,
                       "Use parameterized queries instead of f-string interpolation."))
    print(report.render())

Usage (CLI — pipe JSON findings):
    echo '[{"severity":"critical","title":"SQL injection","file":"srv.py","line":42,"fix":"Use params"}]' \\
        | python generate_review_report.py --target src/auth/service.py
"""

from __future__ import annotations

import json
import sys
from dataclasses import dataclass, field
from datetime import date
from enum import Enum
from typing import Optional


class Severity(str, Enum):
    CRITICAL = "critical"  # Block merge
    WARNING = "warning"  # Fix before next sprint
    SUGGESTION = "suggestion"  # Optional improvement


@dataclass
class Finding:
    severity: Severity
    title: str
    file: str = ""
    line: Optional[int] = None
    fix: str = ""
    owasp_ref: str = ""

    def _location(self) -> str:
        if self.file and self.line:
            return f"`{self.file}:{self.line}`"
        if self.file:
            return f"`{self.file}`"
        return ""

    def render(self, index: int) -> str:
        parts = [f"{index}. **{self.title}**"]
        if loc := self._location():
            parts.append(f"   - Location: {loc}")
        if self.owasp_ref:
            parts.append(f"   - OWASP: {self.owasp_ref}")
        if self.fix:
            parts.append(f"   - Remediation: {self.fix}")
        return "\n".join(parts)


@dataclass
class ReviewReport:
    target: str
    reviewer: str = "Guardian"
    date: str = field(default_factory=lambda: str(date.today()))
    _findings: list[Finding] = field(default_factory=list, repr=False)

    def add(self, finding: Finding) -> "ReviewReport":
        self._findings.append(finding)
        return self

    def verdict(self) -> str:
        if any(f.severity == Severity.CRITICAL for f in self._findings):
            return "❌ FAIL"
        if any(f.severity == Severity.WARNING for f in self._findings):
            return "⚠️  NEEDS WORK"
        return "✅ PASS"

    def verdict_rationale(self) -> str:
        criticals = [f for f in self._findings if f.severity == Severity.CRITICAL]
        warnings = [f for f in self._findings if f.severity == Severity.WARNING]
        if criticals:
            return f"{len(criticals)} critical finding(s) block merge."
        if warnings:
            return f"{len(warnings)} warning(s) must be resolved before next sprint."
        return "No blocking issues found."

    def _section(self, severity: Severity, heading: str) -> str:
        items = [f for f in self._findings if f.severity == severity]
        if not items:
            return f"### {heading}\n\n_None._\n"
        lines = [f"### {heading}\n"]
        for i, finding in enumerate(items, 1):
            lines.append(finding.render(i))
            lines.append("")
        return "\n".join(lines)

    def render(self) -> str:
        return (
            f"# Guardian Review Report\n\n"
            f"**Target**: `{self.target}`  \n"
            f"**Reviewer**: {self.reviewer}  \n"
            f"**Date**: {self.date}  \n"
            f"**Verdict**: {self.verdict()} — {self.verdict_rationale()}\n\n"
            "---\n\n"
            + self._section(Severity.CRITICAL, "Critical (Block Merge)")
            + "\n"
            + self._section(Severity.WARNING, "Warnings (Fix Before Next Sprint)")
            + "\n"
            + self._section(Severity.SUGGESTION, "Suggestions (Optional)")
            + "\n---\n\n"
            "_Report generated by Guardian Skill. "
            "Hand off verdict to `release-manager` for ship/no-ship decision._\n"
        )


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(description="Generate a Guardian review report")
    parser.add_argument("--target", required=True, help="File, module, or PR being reviewed")
    parser.add_argument(
        "--findings",
        type=str,
        default=None,
        help="JSON array of findings (reads stdin if omitted)",
    )
    args = parser.parse_args()

    raw = args.findings or sys.stdin.read()
    findings_data: list[dict] = json.loads(raw) if raw.strip() else []

    report = ReviewReport(target=args.target)
    for item in findings_data:
        report.add(
            Finding(
                severity=Severity(item.get("severity", "suggestion")),
                title=item.get("title", "Unnamed finding"),
                file=item.get("file", ""),
                line=item.get("line"),
                fix=item.get("fix", ""),
                owasp_ref=item.get("owasp_ref", ""),
            )
        )

    print(report.render())


if __name__ == "__main__":
    main()
